Support custom build args
gokrazy/tools pull request #21
Opened 2021-01-09 21:05 UTC by andig

Fix https://github.com/gokrazy/gokrazy/issues/80

2021-01-10 09:39 UTC, stapelberg requested changes
As-is, this pull request enforces the same build options for all applications, which is not necessarily desirable.

Could you instead use the same approach as https://github.com/gokrazy/tools/commit/fdd90fc6817876e08b352fae84f2a2794524ccc0, just for buildflags please?

2021-01-11 12:54 UTC, andig commented
The proposed structure will lead to a lot of directories:

    flags/github.com/gokrazy/timestamps/flags.txt

then becomes:

    buildopt/github.com/gokrazy/timestamps/buildopt.txt

Would you be ok with flattening these and putting the various package-specific options into a single per-packege folder like

    github.com/gokrazy/timestamps/flags.txt
    github.com/gokrazy/timestamps/buildopt.txt

2021-01-11 13:00 UTC, stapelberg commented
> The proposed structure will lead to a lot of directories:

Yes, one per thing that you’re changing.

I like that you can do e.g. `head -100 flags/**/*` (provided your shell expands `**/*`) to see all flags for all packages.

I don’t think that’s a problem, though. I understand that some people might subjectively prefer one or the other.

What I’m shooting for here is maximum clarity, though. All flags go into the flags directory, all environment variables into the environ directory, etc.

2021-01-11 13:47 UTC, andig commented
> I like that you can do e.g. head -100 flags/**/* (provided your shell expands **/*) to see all flags for all packages.

You could do the same by `./**/flags.txt`?

2021-01-11 14:44 UTC, andig commented
LGTM:

    ❯ gor github.com/gokrazy/tools/cmd/gokr-packer -http_port 8080 -update yes -hostname evcc github.com/gokrazy/breakglass github.com/andig/evcc
    2021/01/11 15:40:09 packer.go:458: building [github.com/gokrazy/breakglass github.com/andig/evcc]
    2021/01/11 15:40:09 packer.go:200: package github.com/andig/evcc will be compiled with build args from buildargs/github.com/andig/evcc/buildargs.txt
    [build -tags gokrazy -o /var/folders/73/89ycv7qn51j4kbm04jsz9b840000gn/T/gokrazy-bins-302778475/dhcp github.com/gokrazy/gokrazy/cmd/dhcp]
    [build -tags gokrazy -o /var/folders/73/89ycv7qn51j4kbm04jsz9b840000gn/T/gokrazy-bins-302778475/evcc -tags=release -ldflags '-X "github.com/andig/evcc/server.Version=${VERSION}" -X "github.com/andig/evcc/server.Commit=${SHA}"' github.com/andig/evcc]

2021-01-12 16:52 UTC, stapelberg commented
> You could do the same by `./**/flags.txt`?

Indeed, yes.

I still feel that having a top-level directory for per-package configuration files is a good idea.

2021-01-12 16:55 UTC, stapelberg requested changes

2021-01-12 16:55 UTC, stapelberg commented on cmd/gokr-packer/packer.go
> +			return nil, nil // no package/ directory found
This should be “no fileType directory found”

2021-01-12 16:55 UTC, stapelberg commented on cmd/gokr-packer/packer.go
> +	// no package files found
This comment seems wrong / out-of-place?

2021-01-12 16:55 UTC, stapelberg commented on cmd/gokr-packer/packer.go
> +	buildArgsFilePaths, err := findPackageFiles("buildargs")
Here and elsewhere: this should be `buildflags` (see e.g. `go help build`, which calls them flags, not args)

2021-01-12 20:13 UTC, andig commented
> > You could do the same by `./**/flags.txt`?
> 
> Indeed, yes.
> 
> I still feel that having a top-level directory for per-package configuration files is a good idea.

Maybe packageconf or buildconfig as top level? Then we could at least gather multiple files in the same package folder.

2021-01-13 08:07 UTC, stapelberg approved these changes

2021-01-13 08:07 UTC, merged